package enumerados;

public enum TipoParentesco {

	N_A, CUNHADO, CUNHADA, ESPOSO, ESPOSA, FILHA, FILHO, ENTEADA, 
	NETO, NETA, NAMORADO, NAMORADA, PAI, MAE, IRMAO, IRMA, AVÔ, AVÓ, TIO, TIA,
	SOBRINHO, SOBRINHA, MADRINHA, PADRINHO, AFILHADA, AFILHADO, GENRO, NORA;



}
